services:
  - type: web
    name: uniblox
    env: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build && cd ../backend && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: uniblox
          property: port
